"""Inventory/material helpers shared by scanner and crafting flows."""

import json
import re
from pathlib import Path

import click

from item_parsing.parser import parse_item_text
from windows.inventory import scan_inventory


ROOT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_MATS_FILE = ROOT_DIR / "crafting_mats.json"


def _normalize_name(value: str | None) -> str:
    """Lowercase and collapse a name so substring matching is more reliable."""
    if not value:
        return ""
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()


def _looks_like_same_base(name: str | None, base: str | None, target_base: str) -> bool:
    """Match by normalized containment for cases where the base line is omitted."""
    normalized_target = _normalize_name(target_base)
    normalized_base = _normalize_name(base)
    normalized_name = _normalize_name(name)
    if not normalized_target:
        return False
    return (
        normalized_target in normalized_base
        or normalized_base in normalized_target
        or normalized_target in normalized_name
        or normalized_name in normalized_target
    )


def load_known_mats(path: Path = DEFAULT_MATS_FILE) -> dict:
    """Load the known crafting-material summary generated by `main_test.py --mats`."""
    if not path.exists():
        raise FileNotFoundError(
            "crafting_mats.json not found. Run  py main_test.py --mats  first."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def extract_stack_size(stat_lines: list[str]) -> tuple[int, int]:
    """Return (current, max) stack size from 'Stack Size: X/Y', or (1, 1)."""
    for line in stat_lines:
        match = re.match(r"Stack Size:\s*(\d+)/(\d+)", line, re.IGNORECASE)
        if match:
            return int(match.group(1)), int(match.group(2))
    return 1, 1


def extract_description(raw_text: str) -> str:
    """Extract the descriptive text from a POE currency clipboard block."""
    sections = [section.strip() for section in raw_text.strip().split("--------")]
    desc_lines = []
    for section in sections:
        lines = [line.strip() for line in section.splitlines() if line.strip()]
        for line in lines:
            low = line.lower()
            if low.startswith("right click") or low.startswith("left click"):
                continue
            if re.match(r"stack size:", low):
                continue
            if any(low.startswith(prefix) for prefix in ("item class:", "rarity:")):
                continue
            if not desc_lines and not re.search(r"[.!]", line):
                continue
            if re.search(r"[a-z]", low):
                desc_lines.append(line)
    return " ".join(desc_lines).strip()


def scan_for_mats(
    known_mats: dict,
    hover_delay: float,
    copy_delay: float,
    verbose: bool,
    target_base: str,
) -> tuple[list[dict], list[dict], list[tuple[int, int]]]:
    """Scan all inventory cells and separate crafting mats, matching bases, and empty slots."""
    found_mats: list[dict] = []
    found_bases: list[dict] = []

    def on_item(col: int, row: int, text: str) -> None:
        if col == 0 and row == 0:
            return

        item = parse_item_text(text)
        name = item.get("name") or item.get("base") or "Unknown"
        base = item.get("base") or name

        if _looks_like_same_base(name, base, target_base):
            found_bases.append({
                "col": col,
                "row": row,
                "name": name,
                "base": base,
                "rarity": item["rarity"],
                "item_level": item["item_level"],
            })
            if verbose:
                click.echo(f"  [{col:02d},{row:02d}] {name}  ({base}, extra base found)")
            return

        if name not in known_mats:
            if verbose:
                click.echo(f"  [{col:02d},{row:02d}] {name}  (not a known mat)")
            return

        count, _ = extract_stack_size(item["stat_lines"])
        found_mats.append({
            "name": name,
            "col": col,
            "row": row,
            "count": count,
            "max_stack": known_mats[name].get("max_stack", 1),
            "description": known_mats[name].get("description", ""),
        })
        if verbose:
            click.echo(f"  [{col:02d},{row:02d}] {name}  x{count}")

    result = scan_inventory(
        on_item=on_item,
        hover_delay=hover_delay,
        copy_delay=copy_delay,
        verbose=verbose,
    )

    empty_slots: list[tuple[int, int]] = []
    for row in range(len(result["grid"])):
        for col in range(len(result["grid"][row])):
            if col == 0 and row == 0:
                continue
            if result["grid"][row][col] is None:
                empty_slots.append((col, row))

    return found_mats, found_bases, empty_slots


def combined_scan_for_mats(
    target_base: str,
    hover_delay: float,
    copy_delay: float,
    verbose: bool,
) -> tuple[list[dict], list[dict], list[tuple[int, int]], dict]:
    """Single-pass scan: builds the full material catalog AND finds positioned orbs.

    Uses max_stack > 1 to identify stackable currencies vs equipment.
    Returns (found_mats, found_bases, empty_slots, catalog_dict).
    """
    catalog: dict[str, dict] = {}
    found_mats: list[dict] = []
    found_bases: list[dict] = []

    def on_item(col: int, row: int, text: str) -> None:
        if col == 0 and row == 0:
            return

        item = parse_item_text(text)
        name = item.get("name") or item.get("base") or "Unknown"
        base = item.get("base") or name
        count, max_stack = extract_stack_size(item["stat_lines"])
        desc = extract_description(text)

        if _looks_like_same_base(name, base, target_base):
            found_bases.append({
                "col": col,
                "row": row,
                "name": name,
                "base": base,
                "rarity": item["rarity"],
                "item_level": item["item_level"],
            })
            if verbose:
                click.echo(f"  [{col:02d},{row:02d}] {name}  ({base}, base)")
            return

        if max_stack <= 1:
            return

        if name in catalog:
            catalog[name]["count"] += count
        else:
            catalog[name] = {"count": count, "max_stack": max_stack, "description": desc}

        found_mats.append({
            "name": name,
            "col": col,
            "row": row,
            "count": count,
            "max_stack": max_stack,
            "description": desc,
        })
        if verbose:
            click.echo(f"  [{col:02d},{row:02d}] {name}  x{count}")

    result = scan_inventory(
        on_item=on_item,
        hover_delay=hover_delay,
        copy_delay=copy_delay,
        verbose=verbose,
    )

    empty_slots: list[tuple[int, int]] = []
    for row_idx in range(len(result["grid"])):
        for col_idx in range(len(result["grid"][row_idx])):
            if col_idx == 0 and row_idx == 0:
                continue
            if result["grid"][row_idx][col_idx] is None:
                empty_slots.append((col_idx, row_idx))

    return found_mats, found_bases, empty_slots, catalog
